#ifndef bibliotekos_h
#define bibliotekos_h

#include <iostream>
#include <iomanip>
#include <algorithm>
#include <cstdlib>
#include <ctime>
#include <vector>
#include <fstream>
#include <sstream>
#include <chrono>
#include <cctype>
#include <random>
#include <utility>
#include <assert.h>
#include <map>
#include <set>
#include <string>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::srand;
using std::rand;
using std::vector;
using std::setw;
using std::fixed;
using std::setprecision;
using std::string;
using std::sort;
using std::istringstream;
using std::ifstream;
using std::ofstream;
using std::exception;
using std::numeric_limits;
using std::streamsize;
using std::runtime_error;
using std::cerr;
using std::move;
using std::ostream;
using std::istream;
using std::accumulate;
using std::map;
using std::pair;
using std::set;
using std::stringstream;
#endif /* biblioteka_h */
